# Generated by Django 5.1 on 2024-09-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='max_gusts',
            new_name='max_guests',
        ),
    ]
